#ifndef COMPONENTS_VERSION_VERSION_HPP_IN
#define COMPONENTS_VERSION_VERSION_HPP_IN

// <VERSION_MAJOR>.<VERSION_MINOR>.<VERSION_PATCH>-<VERSION_SUFFIX>

#define ESP32_FIRMWARE_VERSION "0.1.0"

#endif  // COMPONENTS_VERSION_VERSION_HPP_IN
