stages:
    - build

esp32:
    image: "${CI_REGISTRY}/pioneermini/esp32cam/ubuntu20.04-deps:v4.4.1"
    stage: build
    script:
        - git submodule | awk '{print $2}' | grep -v espidf | xargs -n 1 git submodule update --init --recursive
        - rm -r espidf
        - ln -s $IDF_PATH
        - . $IDF_PATH/export.sh && idf.py build
        - cd tools && ./extract_binaries.sh
    artifacts:
        name: $(echo $CI_JOB_NAME | sed 's~/~_~;s~esp32:~~;')_$CI_COMMIT_SHORT_SHA
        paths:
            - "./tools/*.bin"
