variables:
    GIT_SUBMODULE_STRATEGY: recursive


platformio_build:
    image: ${CI_REGISTRY_IMAGE}:ubuntu 
    script:
        - platformio run
    when: manual

espidf_build:
    image: ${CI_REGISTRY_IMAGE}:ubuntu
    before_script:
        - export PATH=/root/xtensa/bin:$PATH
    script:
        - python /root/esp-idf/tools/idf.py build
        - cd tools
        - ./extract_binaries.sh
    artifacts:
        paths:
            - "./tools/*.bin"

espidf_build_deps:
    image: ${CI_REGISTRY_IMAGE}:ubuntu
    script:
        - export PATH=`echo $PATH | sed 's/[^:]*esp32[^:]*:/:/g'`
        - echo $PATH
        - make configure
        - make build
        - cd tools
        - ./extract_binaries.sh
    artifacts:
        paths:
            - "./tools/*.bin"
    when: manual
