default:
    image: ${CI_REGISTRY_IMAGE}:latest 
    before_script:
        - source ~/esp-idf/export.sh

platformio_build:
    script:
        - platformio run

espidf_build:
    script:
        - idf.py set-target esp32
        - idf.py build