#!/bin/bash

if [ -z "$2" ] ; then
	echo Usage: $(basename ${BASH_SOURCE[0]}) COMPONENT_FRAME COMPONENT_FRAME_NAMESPACE
	exit 1
fi

COMPONENT_FRAME=$1
COMPONENT_FRAME_NAMESPACE=$2
TEMPLATE_DIRECTORY_PATH=$(realpath $PWD)
PROJECT_COMPONENTS_PATH=$(realpath "../../components")

mkdir -p ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME}/${COMPONENT_FRAME}
cp ${TEMPLATE_DIRECTORY_PATH}/CMakeLists.txt ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME}
cp ${TEMPLATE_DIRECTORY_PATH}/Kconfig.projbuild ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME}
cp ${TEMPLATE_DIRECTORY_PATH}/component_frame.cpp ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME}/${COMPONENT_FRAME}/${COMPONENT_FRAME}.cpp
cp ${TEMPLATE_DIRECTORY_PATH}/component_frame.hpp ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME}/${COMPONENT_FRAME}/${COMPONENT_FRAME}.hpp
touch ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME}/README.md

export COMPONENT_FRAME_DATE=`date +%Y-%m-%d` \
	&& find ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME} -type f | xargs -n 1 sed -i "s/COMPONENT_FRAME_DATE/${COMPONENT_FRAME_DATE}/g"
export COMPONENT_FRAME_UPPER=`echo ${COMPONENT_FRAME} | tr a-z A-Z` \
	&& find ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME} -type f | xargs -n 1 sed -i "s/COMPONENT_FRAME_UPPER/${COMPONENT_FRAME_UPPER}/g"
find ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME} -type f | xargs -n 1 sed -i "s/COMPONENT_FRAME_NAMESPACE/${COMPONENT_FRAME_NAMESPACE}/g"
find ${PROJECT_COMPONENTS_PATH}/${COMPONENT_FRAME} -type f | xargs -n 1 sed -i "s/COMPONENT_FRAME/${COMPONENT_FRAME}/g"
