//
// RtspRequestHandler.cpp
//
// Created on:  Aug 24, 2020
// Author: Dmitry Murashov (d.murashov@geoscan.aero)
//

#include "RtspRequestHandler.hpp"

extern void parse(Rtsp::Request &, const Rtsp::Data); // Parser generated by gnu flex/bison

const Rtsp::Data RtspRequestHandler::handle(const Rtsp::Data data)
{
	Rtsp::Request request;
	parse(request, data);

	switch (request.requestType.val()) {

		case Rtsp::RequestType::Play:
			return handlePlay(request);

		case Rtsp::RequestType::Describe:
			return handleDescribe(request);

		case Rtsp::RequestType::Setup:
			return handleSetup(request);

		case Rtsp::RequestType::Pause:
			return handlePause(request);

		case Rtsp::RequestType::Teardown:
			return handleTeardown(request);

		default:
			return handleNotStated(request);
	}
}


const Rtsp::Data RtspRequestHandler::handlePlay(const Rtsp::Request &)
{
	return {nullptr, 0};
}

const Rtsp::Data RtspRequestHandler::handleDescribe(const Rtsp::Request &)
{
	return {nullptr, 0};
}

const Rtsp::Data RtspRequestHandler::handleSetup(const Rtsp::Request &)
{
	return {nullptr, 0};
}

const Rtsp::Data RtspRequestHandler::handlePause(const Rtsp::Request &)
{
	return {nullptr, 0};
}

const Rtsp::Data RtspRequestHandler::handleTeardown(const Rtsp::Request &)
{
	return {nullptr, 0};
}

const Rtsp::Data RtspRequestHandler::handleNotStated(const Rtsp::Request &)
{
	return {nullptr, 0};
}